---
- name: Crear clave SSH y copiarla a Bitbucket
  hosts: SUMA-servers
  tasks:
    - name: Generar clave SSH
      command: ssh-keygen -t rsa -b 4096 -C "cesarcalderon@sumawealth" -f /home/ubuntu/.ssh/id_rsa -q -N ""

    - name: Obtener clave pública
      command: cat /home/ubuntu/.ssh/id_rsa.pub
      register: public_key

    - name: Mostrar clave pública (solo para verificar)
      debug:
        var: public_key.stdout

    # En esta parte deberías implementar la lógica para copiar la clave pública a Bitbucket.
    # Esto puede variar dependiendo de cómo Bitbucket maneje el manejo de claves SSH.

    # Después de este playbook, deberías haber copiado la clave pública generada a tu cuenta de Bitbucket.