---
- name: Clonar repositorio
  hosts: SUMA-servers
  become: yes

  tasks:
    - name: Crear directorio projects
      file:
        path: "~/projects"
        state: directory
      become_user: ubuntu

    # - name: Agregar clave del host de Bitbucket al known_hosts
    #   lineinfile:
    #     dest: "/home/ubuntu/.ssh/known_hosts"
    #     line: "{{ lookup('pipe', 'ssh-keyscan bitbucket.org') }}"
    #     create: yes
    #   become_user: ubuntu

    # - name: Clonar repositorio Git
    #   git:
    #     repo: "git@bitbucket.org:so4reeel/suma-api"
    #     dest: "~/projects/suma-api"
    #     version: develop
    #   become_user: ubuntu

    - name: Clonar repositorio de Bitbucket
      shell: |
        cd /home/ubuntu/projects
        git clone --branch develop git@bitbucket.org:so4reeel/suma-api
