---
- name: Clonar repositorio desde Bitbucket
  hosts: SUMA-servers
  tasks:
    - name: Crear directorio para el proyecto
      file:
        path: /home/ubuntu/projects
        state: directory
        mode: '0755'

    - name: Clonar repositorio
      git:
        repo: git@bitbucket.org:so4reeel/suma-api
        dest: /home/ubuntu/projects/suma-api
        accept_hostkey: yes
        key_file: /home/ubuntu/.ssh/id_rsa
        force: yes
        version: develop
